[project]
authors = [{name = "Johannes Lohse", email = "johannes.lohse@utas.edu.au"}]
dependencies = [
    "geopandas>=1.1.3,<2", 
    "numpy>=2.2.6,<3", 
    "scipy>=1.18.0,<2", 
    "matplotlib>=3.11.0,<4", 
    "pyyaml>=6.0.3,<7", 
    "rioxarray>=0.22.0,<0.23", 
    "odc-stac[botocore]>=0.5.2,<0.6", 
    "odc-geo>=0.5.1,<0.6", 
    "stac-geoparquet>=0.8.0,<0.9", 
    "xarray>=2026.4.0,<2027", 
    "pystac>=1.14.3,<2", 
    "pystac-client>=0.9.0,<0.10", 
    "fsspec>=2026.6.0,<2027", 
    "aiohttp>=3.14.1,<4", 
    "ipykernel>=7.3.0,<8", 
    "loguru>=0.7.3,<0.8",
    ]
name = "normalized-covariance"
requires-python = ">=3.11, <3.14"
version = "0.2.1"

[project.urls]
Homepage = "https://github.com/jlo031/normalized_covariance"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64"]

[tool.pixi.pypi-dependencies]
normalized_covariance = { path = ".", editable = true }

[tool.pixi.tasks]
export-conda = """
pixi workspace export conda-environment environment.yaml --environment default && \
sed -ix "s/^name: .*/name: NORMCOVAR/" environment.yaml; rm environment.yamlx
"""

[tool.pixi.dependencies]
python = ">=3.11,<3.14"
gdal = ">=3.10.3,<4"
rasterio = ">=1.4.3,<2"
